---
name: Codebuild (us-east-2)
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
    branches: [main]

env:
  RUN_CODEBUILD: ./.github/bin/run_codebuild.sh  ${{ github.repository }} pr/${{ github.event.number }} us-east-2

jobs:
  setup:
    name: Setup credentials
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          role-to-assume: ???
          role-session-name: ???
          aws-region: us-east-2

  run:
    runs-on: ubuntu-latest
    needs: setup
    matrix:
      project:
        - Integv2NixBatchBF1FB83F-7tcZOiMDWPH0
    steps:
      - run: |
          ${{env.RUN_CODEBUILD}} ${{matrix.project}}

