---
name: Codebuild

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
    branches: [main]

jobs:
  us-west-2:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        project:
          - AddressSanitizer
          - S2nIntegrationV2SmallBatch
          - Valgrind
          - s2nFuzzBatch
          - s2nGeneralBatch
          - s2nUnitNix
          - kTLS
    steps:
      - uses: actions/checkout@v4
      - name: Get credentials
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          role-to-assume: arn:aws:iam::024603541914:role/GitHubOIDCRole
          role-session-name: test
          aws-region: us-west-2
      - name: Run Codebuild job
        run: |
          ./.github/bin/run_codebuild.sh \
              ${{ github.repository }} \
              ${{ github.sha }} \
              us-west-2 \
              ${{matrix.project}}

  us-east-2:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        project:
          - Integv2NixBatchBF1FB83F-7tcZOiMDWPH0
    steps:
      - uses: actions/checkout@v4
      - name: Get credentials
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          role-to-assume: arn:aws:iam::024603541914:role/GitHubOIDCRole
          role-session-name: test
          aws-region: us-east-2
      - name: Run Codebuild job
        run: |
          ./.github/bin/run_codebuild.sh \
              ${{ github.repository }} \
              ${{ github.sha }} \
              us-east-2 \
              ${{matrix.project}}