---
name: Codebuild

on:
  push:
    branches: [main]
  pull_request_target:
    branches: [main, main_yes_lrstewart]
  merge_group:
    types: [checks_requested]
    branches: [main]

jobs:
  start:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      source_pr: pr/${{ github.event.pull_request.number }}
      source_sha: ${{ github.sha }}
      pr_author: ${{ github.event.pull_request.user.login }}
    steps:
      - uses: actions/checkout@v4

      - name: Start Codebuild for SHA
        if: github.event_name != 'pull_request_target'
        run: ./codebuild/bin/start_codebuild.sh $source_sha

      - name: Start Codebuild for PR
        if: github.event_name == 'pull_request_target'
        run: |
          pattern="^  - '@$pr_author'$"
          if grep "$pattern" .github/teams.yml; then
            ./codebuild/bin/start_codebuild.sh $source_pr
          else
            echo "$pr_author is not part of s2n-core."
            echo "A member of s2n-core will need to start the Codebuild jobs manually using the start_codebuild.sh script."
          fi
